# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 01:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0002_auto_20170824_0043'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='User',
        ),
    ]
